### ISSUE TITLE
[Suggestion] Overload AddKey and AddKeys with additional argument for IPFS hash

### ISSUE THREAD

**Issue by Kyrrui** [EthWorks/UniversalLoginSDK#86]
Since we want to be storing and displaying information about the users devices - (Browser, Operating System, Location) - we need to either create a centralized data store which maps public keys to information about users devices OR I propose we:
1. Overload AddKey and AddKeys to include `string _ipfsAdditionalData` and `string [] _ipfsAdditionalData` respectively.
2. Store json blob about device, push it to an ipfs node, and then use this to display info to the user.

This gets us away from the traditional paradigm of storing user data and keeps us more decentralized.

Thoughts and comments?

**Comment by alexvandesande** [comment]
My problem with that is that it's (1) more expensive to store blobs and (2) potentially leaks private information about which devices you use. Here's what I would suggest:

A) Don't keep any private info about keys anywhere. Just save locally and that's ok.

B) We start with A but then: have each key sign a message with all the local information they have about the devices and other meta information, with the public key of the other local keys, so that only other authorized devices can read it. Send that information via the relayers that will share the information back. Since the info is encrypted, the relayers won't know the data, will just be transferring data around

C) B but using decentralized Whisper nodes!

D) isn't uPort building some sort of private box that is able to keep data about a user but is only readable by the user? Just wait for them and we can store all meta info on the same thing

**Comment by Kyrrui** [comment]
I don’t think it is that expensive to use ipfs + ethereum log to store this information, but I do agree it risks leaking user information. For now I will build it with info just stored locally
